join-message:
  enabled: true

  default: "&7[+] &f%player% joined the server"

  # Order = priority (TOP = highest)
  # You Can use %prefix% placeholder to use %luckperms_prefix$.
  ranks:
    admin:
      permission: "joinmessages.admin"
      message: "&c[ADMIN] &f%player% joined the server"

    vip:
      permission: "joinmessages.vip"
      message: "&a[VIP] %player% &6slid in the lobby!"
  
